### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by m-pauper** [BennyStrobes/Watershed#4]
Hello,

First, apologies for the generic title, I wanted to leave it open-ended as I think I have various questions and maybe more when you've replied the existing ones.

Second, my compliments on this tool and the accompanying publication. This repository seems to not have seen much activity, but I still hope to get some clarifications! 

Here go my questions:
1. In the supplementary methods of the publication, it is described that the expression, allele-specific expression and splicing outlier signals were converted to categorical data (based on some thresholds). Is this necessary? The example input in this repository does not seem to include that? Or is this categorization done upon running Watershed?
2. What would be the benefit to re-train Watershed on one's data? Couldn't others use the model you have trained with your own data? Provided they work with the same phenotypic data i.e., expression, allelic-expression and splicing values.
3. Once trained, the model can be used for posterior predictions on all other rare variants: that is all the ones that are 10Kb away from a gene but did not meet the other criteria to be included in the training dataset?
4. The genomic annotations for the training data were transformed to gene-level annotations and the prediction input file "_must be the same structure (ie. same genomic annotations and same outlier calls) as the $training_input_file"_. How are genomic annotations re-transformed to be SNV-level annotations for each (gene, SNV, individual)? I can see how for most it is possible, but taking an example from Table S3, how do you convert "num_rare_variants" to SNV-level annotation?

I'll edit or comment with more questions as they come up. Thanks in advance!

**Comment by BennyStrobes** [comment]
Hello,

Thanks for your interest in using Watershed and your questions.

1.  Yes. Sorry this was unclear. Categorization is done by the Watershed code. All you need to do is enter p-values, and our code will place it into bins.
2. The rationale is the categorical distributions defined by P(E|Z) is somewhat dependent on your data set. For example, P(E|Z) is quite different when Watershed was trained on median outlier data (cross tissue; Fig 4A-D in Watershed paper) compared to tissue outlier data (single tissue; Fig 4E in Watershed paper). We would also expect differences in P(E|Z) in different tissues and sequencing platforms.  Plus, you already have the necessary data to train the Watershed if you are considering evaluating with Watershed.
3. Yes, all variants within 10KB of genes you have outlier data for. Also, as Watershed is unsupervised, you can include your training variants in the predictions files (as long as you are not looking to do some type evaluation based on outlier status and simply just trying get Watershed posteriors on all of your rare variants).
4. If you look at table S3, there is a column called "Transformation to make annotation gene level". This describes the transformations we used. And, as you can see, I used "sum" to make "num_rare_variants" gene level.. similar in theory to burden testing.

Please let me know if you have any other questions.

**Comment by m-pauper** [comment]
Thanks for the quick reply, I really appreciate it!

> Plus, you already have the necessary data to train the Watershed if you are considering evaluating with Watershed.

True, I just haven't checked yet and I am unsure how many variants would meet the criteria to make a sizeable training set. 

> And, as you can see, I used "sum" to make "num_rare_variants" gene level.. similar in theory to burden testing.

I understand how the transformation worked to get you to a gene-level (sum of rare variants near the gene) but my question is: what is the equivalent of that annotation when you use variant-level annotations in the predictions input file? Just num_rare_variants = 1 for each line? The predictions input file should be (RV, Gene,Individual), a set of G annotations, and E phenotypic data. I assumed then that G annotations are at the RV level, but maybe I am wrong?

**Comment by BennyStrobes** [comment]
1. How many individuals do you have data for? I imagine a fair amount if you were able to make expression outlier calls? Or did you use gtex as a reference for outlier calling?

2. I see. 'num_rare_variants' is actually number of copies of the rare allele. So an individual can, in fact, be homozygous for the rare allele, so the the predictions file (where each instance corresponds to a (RV, gene, individual)) should be just the number of copies of the rare allele that the individual has at that RV (ie. so an individual with a homozygous RV would equal 2). And yes, G annotations are at the RV level for the predictions file. As you can see, this is a bit of a "hack" on our end to extract Watershed posterior predictions at the variant level. In general, however, this is approach will give conservative estimates of the Watershed posteriors as Genomic annotations at the variant level will be "less extreme" (due to the transformations we used in table S3) than Genomic annotations for the gene level. 

Another valid option for making predictions with Watershed is to make predictions at the (Gene, Individual) level, for all genes such that the individual has at least 1 variant. This would require a superset of the training data (but in the same (gene,individual) style format).  This is also fine to do, and we have found in practice it is usually easy to identify the causal RV from a high Watershed posterior (gene, individual) pair with multiple RV near the gene based on genomic annotations. However, this approach is not as scalable and deterministic as the approach described in the paper.

**Comment by m-pauper** [comment]
Great. Many thanks for the clear explanations!
